import { Plan } from "./plan";

export class User {
    id?: number;
    firstName: string;
    lastName: string;
    email: string;
    username?: string;
    password: string;
    plans?: Plan[];
    
    constructor (
        id: string,
        firstName: string,
        lastName: string,
        email: string,
        username: string,
        password: string,
        plans: Plan[]
    ) {
        // this.id = undefined; // id will be generated by the database upon creation of the user.
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.plans = plans;
    }

    
}
